# Generated by Django 5.2.1 on 2025-06-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_orderitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pin_code',
        ),
    ]
