# Generated by Django 5.2.1 on 2025-06-13 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_rename_email_order_full_name_remove_order_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amout_paid',
            new_name='amount_paid',
        ),
    ]
